SELECT * FROM ERS_REIMBURSEMENT_STATUSES ERS;
SELECT * FROM ERS_REIMBURSEMENT_TYPES ERT;
SELECT * FROM ERS_USER_ROLES EUR;
SELECT * FROM ERS_USERS EU;
SELECT * FROM ERS_REIMBURSEMENTS ER; 

SELECT * FROM ERS_USERS WHERE USERNAME = 'defaultAdmin' AND PASSWORD = 'passw0rd';

SELECT EU.user_id, EU.username, EU.email, EU.given_name, EU.surname, EU.is_active, EU.role_id, EUR.role FROM ERS_USERS EU JOIN ERS_USER_ROLES EUR ON EU.role_id = EUR.role_id;

SELECT EU.user_id, EU.username, EU.email, EU.given_name, EU.surname, EU.is_active, EU.role_id, EUR.role 
FROM ERS_USERS EU 
JOIN ERS_USER_ROLES EUR 
ON EU.role_id = EUR.role_id
WHERE EU.username = 'defaultAdmin';

SELECT ER.REIMB_ID, ER.AMOUNT, ER.SUBMITTED, ER.DESCRIPTION, EU.USERNAME , ERS.STATUS , ERT."type"  
FROM ERS_REIMBURSEMENTS ER 
JOIN ERS_USERS EU 
ON ER.AUTHOR_ID = EU.USER_ID 
JOIN ERS_REIMBURSEMENT_TYPES ERT  
ON ER.TYPE_ID = ERT.TYPE_ID 
JOIN ERS_REIMBURSEMENT_STATUSES ERS 
ON ER.STATUS_ID = ERS.STATUS_ID ;

SELECT ER.REIMB_ID, ER.AMOUNT, ER.SUBMITTED, ER.DESCRIPTION, EU.USERNAME , ERS.STATUS , ERT."type"  
FROM ERS_REIMBURSEMENTS ER 
JOIN ERS_USERS EU 
ON ER.AUTHOR_ID = EU.USER_ID 
JOIN ERS_REIMBURSEMENT_TYPES ERT  
ON ER.TYPE_ID = ERT.TYPE_ID 
JOIN ERS_REIMBURSEMENT_STATUSES ERS 
ON ER.STATUS_ID = ERS.STATUS_ID 
WHERE ERS.STATUS_ID = '1'
ORDER BY REIMB_ID ;

SELECT REIMB_ID, AMOUNT, SUBMITTED, RESOLVED, DESCRIPTION, AUTHOR_ID, RESOLVER_ID, STATUS_ID, type_id FROM ERS_REIMBURSEMENTS ER
WHERE AUTHOR_ID = '3' ORDER BY REIMB_ID ; 


SELECT EU.user_id, EU.username, EU.email, EU.given_name, EU.surname, EU.is_active, EUR.role FROM ERS_USERS EU JOIN ERS_USER_ROLES EUR ON EU.role_id = EUR.role_id
ORDER BY EU.user_id;
